Return status in check mode
ansible-collections/community.kubernetes pull request #192
Opened 2020-08-13 05:07 UTC by Geethree

##### SUMMARY
In check mode, it is useful to know both what the current values of the release are, and the proposed values of the release based on the state of the playbook.

Addresses : #188 

##### ISSUE TYPE
- Feature Pull Request

##### Questions

- `current` and `proposed` feel a little off in terms of ansible norms, any suggestions for something "better"?
- What would be the best way to address this in the documentation? Maybe adding another values('check_mode') key?

2020-08-13 18:35 UTC, Geethree commented
Hmm. I'll figure out how to get these test to run locally here in a day or two.

2020-09-22 21:28 UTC, tima commented
recheck

2020-09-22 21:29 UTC, geerlingguy commented
@tima heh... that doesn't work in this repo. I'll rerun the tests.

2020-09-22 21:46 UTC, tima commented
@geerlingguy: bah! and i thought i was so smart.

2020-09-24 16:45 UTC, fabianvf commented on plugins/modules/helm.py
> +            status=check_status
```suggestion
            status=check_status,
```

2020-09-24 17:18 UTC, fabianvf commented on plugins/modules/helm.py
> +        }
```suggestion
```

2020-09-24 17:18 UTC, fabianvf commented on plugins/modules/helm.py
> +            }
```suggestion
```

2020-09-24 17:57 UTC, fabianvf commented
@geerlingguy got tests passing

2020-09-27 19:45 UTC, tima commented
@Geethree:

> current and proposed feel a little off in terms of ansible norms, any suggestions for something "better"?

Instead of "proposed" what about "desired" or "declared"? Those are terms we use a lot while talking about Ansible and idempotency. We use "current state" a lot though so that one seems fine to me.

2020-09-28 20:26 UTC, tima requested changes

2020-09-28 20:26 UTC, tima commented on plugins/modules/helm.py
> +            "proposed": release_values
I'd suggest using "desired" instead of "proposed" here.

2020-09-28 20:55 UTC, Geethree commented
Hello. Apologies for the delay in response, and thank you to @fabianvf for finding the failure there.

I kind of like your suggestion of "proposed" @tima. Would you like to do so @fabianvf or I could step in as well? Just want to make sure we do not step on one other's toes.

2020-09-28 21:27 UTC, tima commented
Actually, @Geethree I suggested "declared" *instead* of "proposed".

2020-09-29 15:11 UTC, fabianvf commented on plugins/modules/helm.py
> +            "proposed": release_values
```suggestion
            "desired": release_values
```

2020-09-29 15:12 UTC, geerlingguy commented
lgtm

2020-09-29 15:15 UTC, maxamillion approved these changes

2020-09-29 15:15 UTC, geerlingguy approved these changes

2020-09-29 18:08 UTC, tima approved these changes

2020-09-29 18:09 UTC, merged