Remove KubernetesAnsibleModule
ansible-collections/community.kubernetes pull request #227
Opened 2020-09-09 12:23 UTC by Akasurde

##### SUMMARY

* Make a AnsibleMixin parent class for every module
* Remove KubernetesAnsibleModule class
* Modified k8s_log

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
plugins/module_utils/common.py
plugins/modules/k8s_log.py

2020-09-09 14:13 UTC, geerlingguy reviewed
The structure of the change looks okay to me, though the change seems to have introduced a cascade of test failures. Assuming we resolve those I'm fine with this change.

I haven't taken a peek, but do you know if anything in the Kubevirt modules in `community.general` would blow up after making these changes; I noticed they import from `KubernetesRawModule`.

2020-09-09 14:29 UTC, Akasurde commented
> The structure of the change looks okay to me, though the change seems to have introduced a cascade of test failures. Assuming we resolve those I'm fine with this change.
> 

Yes, Since we removed KubernetesAnsibleModule from only one module, the rest are in pipeline.

> I haven't taken a peek, but do you know if anything in the Kubevirt modules in `community.general` would blow up after making these changes; I noticed they import from `KubernetesRawModule`.

Good. Thanks for reminding me that. I will take care of that as well once this is resolved.

2020-09-11 14:29 UTC, geerlingguy approved these changes
LGTM, but I would like to make sure at least one or two other maintainers deeper into any other module integrations (I know of kubevirt that might need adjustments, but I don't know if anyone else might be relying on `KubernetesAnsibleModule`...?).

The other question: would this be something we can merge into a 1.1, or do we need to go to 2.0.0 with this change?

2020-09-11 15:14 UTC, maxamillion approved these changes
LGTM :+1:

2020-09-15 15:29 UTC, tima commented
@fabianvf could you weigh in on a dummy class here to avoid breaking anyone.

2020-09-15 17:38 UTC, fabianvf commented on plugins/module_utils/common.py
> -class KubernetesAnsibleModule(AnsibleModule, K8sAnsibleMixin):
We can probably leave this and the `KubernetesRawModule` classes around as dummies with warnings to avoid a breaking API change

2020-09-15 18:43 UTC, fabianvf requested changes
Sorry that last review should have been marked as `Request changes`

2020-09-16 14:32 UTC, fabianvf approved these changes

2020-09-16 15:05 UTC, merged

2020-10-09 13:36 UTC, felixfontein commented
I think this PR breaks the unit tests in community.general (see f.ex. https://app.shippable.com/github/ansible-collections/community.general/runs/4278/15/tests). Could someone please check whether this also affects the kubevirt modules?

2020-10-10 04:03 UTC, Akasurde commented
@felixfontein I have raised a PR to fix failing kubevirt tests.

2020-10-10 04:04 UTC, Akasurde commented
Community.general - https://github.com/ansible-collections/community.general/pull/1070