k8s: Add a parameter remote_src
ansible-collections/community.kubernetes pull request #320
Opened 2020-12-03 10:30 UTC by Akasurde

##### SUMMARY

remote_src is boolean parameter to specify if
src file is located on remote node or Ansible Controller.

Fixes: #307

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
changelogs/fragments/307_remote_src.yml
plugins/action/k8s_info.py
plugins/doc_fragments/k8s_resource_options.py
plugins/module_utils/common.py

2020-12-03 18:16 UTC, fabianvf commented on plugins/action/k8s_info.py
> +            if remote_src:
Do we want to do something for `kubeconfig` as well? It's a bit awkward but that is another file that we look for locally but could be present remotely.

2020-12-04 07:05 UTC, Akasurde commented
recheck

2020-12-04 12:50 UTC, sylvainOL commented
one of two issues of #307 is solved thanks to this PR. 👍

2020-12-04 17:53 UTC, tima requested changes
I'm not a fan of this implementation. I'm pretty sure when I wrote the synchronize I was able to figure this out in the code without an extra param.

2020-12-08 15:48 UTC, gravesm approved these changes
LGTM

2020-12-09 15:30 UTC, goneri commented on plugins/action/k8s_info.py
> +            remote_transport = True
`remote_transport = self._connection.transport != 'local'`

2020-12-09 15:49 UTC, fabianvf requested changes

2020-12-09 15:49 UTC, fabianvf commented on plugins/action/k8s_info.py
> +        if self._connection.transport != 'local':
Could you add some docs to the module describing exactly what the behavior users will see is? I don't know much about how Ansible handles all this stuff internally so I'm not really sure when it'll try to load it locally vs remotely

2020-12-09 15:52 UTC, fabianvf approved these changes

2020-12-09 15:53 UTC, fabianvf commented on plugins/action/k8s_info.py
> +        if self._connection.transport != 'local':
Changing my review to approving because I might not get back to this in a reasonable amount of time, but still requesting some docs

2020-12-09 19:27 UTC, tima approved these changes
LGTM once @goneri and @fabianvf comments are addressed.

2020-12-10 17:22 UTC, goneri approved these changes

2020-12-10 17:58 UTC, merged

2020-12-10 18:08 UTC, goneri commented
Thank you @Akasurde :-).