helm: use the diff generated before
ansible-collections/community.kubernetes pull request #363
Opened 2021-02-04 20:07 UTC by joschi36

##### SUMMARY
In the previous PR #355 @Akasurde has implemented optional helm check by the helm plugin diff.
I was unsure why we would not use this for --diff in Ansible. This would be very useful.
I have added a gist with a simple module I build which is actually using it.
Also, I think this PR needs some more love, but first I wanted to gather a little bit of feedback from the original creator @Akasurde and @LucasBoisserie 

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

Helm

##### ADDITIONAL INFORMATION
Also, I sorted parameters in `exit_json`

2021-02-04 20:36 UTC, tima commented
Thanks for the PR @joschi36. CI failures aside I had a couple of comments.

Should the presence of the diff be conditional on the presence of `--diff`? I'm not seeing that here. Also, since `helm-diff` is optional to this module, what is returned if `--diff` is used?

2021-02-04 20:55 UTC, joschi36 commented
Thanks @tima for the quick feedback.

First sorry I've forgotten to add the gist I was talking about: https://gist.github.com/joschi36/f7df3a0aac460cebe11c36ec1b9a03bf
That's the module we are currently using in production.

> Should the presence of the diff be conditional on the presence of --diff?

I'm not sure if this is needed. If the `--diff` parameter is not present the diff is not showed. I'm not sure if it should be conditional.

> Also, since helm-diff is optional to this module, what is returned if --diff is used?

No diff as before. When variable diff is empty it will result in:
`diff={'prepared': ''},` in `exit_json` and just no diff is shown.

I hope I understood your questions right, it's getting late here :smile:

2021-02-09 14:59 UTC, gravesm requested changes
Thanks for the PR @joschi36. Aside from the linting error we'll need a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment).

This looks good, though, and is a nice addition!

2021-02-09 14:59 UTC, gravesm commented on plugins/modules/helm.py
>                                                release_values, values_files, chart_version, replace)
The indentation here needs to be corrected in order to address the linting error.

2021-06-07 07:48 UTC, Akasurde commented
@joschi36 Thanks for the contribution. Could you open a new PR against https://github.com/ansible-collections/kubernetes.core? Thanks.

2021-06-07 07:48 UTC, closed without merging